### PR TITLE
fixing python compile error

### PR DESCRIPTION
**Pull request by janm31415**
Fixing Python ImportError: cannot import name 'Mapping' from 'collections'

### CODE REVIEW

**Review by jatinchowdhury18 — APPROVED** [review]
Nice, the Python change seems fine. I'm happy to merge it pending the current CI runs.

For the netlist, I usually keep those out of the repository unless they're specifically being used for testing purposes, but I am a bit curious about the circuit you're working on?

**Comment by janm31415** [comment]
Hi Jatin,

I'm working on the Contour knob of a Marshall Valvestate amplifier, see
attachment.
It's all new to me as I don't know anything about electronics, but I've
been reading the papers on WDF.
The circuit I extracted looks like this:
--Vin---C1--R1---|--------C2----------|
                            |                              |
                            |---R2----|----R3---|
                            |              |               |
                           C3          C4             R5
                            |              |               |
                            |             R4+          |---- Vout
                            |               |              |
                            |----------|           ground
                            |               |
                           C5           R4-
                            |               |
                        ground    ground
When making a SPQR tree, I got an R-type node with 8 branches. Something
like

R --> S1 --> Vin
               --> S2 --> C1
                          --> R1
  --> R2
  --> R3
  --> C3
  --> S3 --> R4+
             --> C4
  --> P1 --> R4-
              --> C5
  --> C2
  --> R5

The netlist I used is like this:
Va 1 6
Vb 4 7
Vc 3 8
Vd 4 9
Ve 2 10
Vf 2 11
Vg 4 12
Vh 5 13
Ra 4 6
Rb 3 7
Rc 5 8
Rd 2 9
Re 3 10
Rf 1 11
Rg 5 12
Rh 1 13
(made using your blog post)
where subscripts a...h correspond with the order in the SPQR tree above.

Greets,
Jan

Valvestate_ContourCircuit

Op wo 1 feb. 2023 om 01:34 schreef jatinchowdhury18 <
***@***.***>:

**Comment by jatinchowdhury18** [comment]
Oh very cool! The schematic got a little mangled in the GitHub issue, but I think I get what you're going for! Anyway, I'd be curious to hear what it sounds like once you've got it working :).

That said, would it be possible to remove the netlist from this PR? I'd prefer to keep the netlists in this repo fairly minimal. For my own work, I have a `scratch/` directory (which is git-ignored) to hold all the netlists I'm working on for personal stuff.

**Comment by janm31415** [comment]
Ah, I thought the pull request would only contain my first commit. Still learning how to use git :)
I've removed the netlist and fixed a bit the schematic for the GitHub lettertype.

**Pull request merged**
